/********************************************************************************
** Form generated from reading UI file 'MPS.ui'
**
** Created by: Qt User Interface Compiler version 6.5.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MPS_H
#define UI_MPS_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MPS
{
public:
    QWidget *centralwidget;
    QPushButton *p1_9;
    QPushButton *Cinnabon;
    QPushButton *p1_0;
    QPushButton *CoffeeBoy;
    QPushButton *Exit;
    QPushButton *p5_0;
    QPushButton *Pharamacy;
    QPushButton *OpposeMain;
    QPushButton *Shabrawy;
    QPushButton *N_;
    QPushButton *p3_0;
    QPushButton *K_;
    QPushButton *Entry;
    QPushButton *Booth;
    QPushButton *p2_4;
    QPushButton *p9;
    QPushButton *Main;
    QPushButton *sideMain;
    QPushButton *TBS;
    QPushButton *p1_5;
    QPushButton *StaffEntry;
    QPushButton *p1_8;
    QPushButton *R2GO;
    QPushButton *Reception;
    QPushButton *Manousha;
    QPushButton *Mosque;
    QPushButton *Faraghly;
    QPushButton *p1_1;
    QPushButton *p3_5;
    QPushButton *S_;
    QPushButton *MiniMarket;
    QPushButton *p3_4;
    QPushButton *p3_7;
    QPushButton *p3_6;
    QPushButton *p3_2;
    QPushButton *p3_3;
    QPushButton *SideS;
    QPushButton *R_;
    QPushButton *BatatesandZalabya;
    QPushButton *Sbarro;
    QPushButton *FootballField;
    QPushButton *BasketBallCourt;
    QPushButton *Clinic;
    QPushButton *p3_8;
    QPushButton *p3_9;
    QPushButton *p4_4;
    QPushButton *p4_5;
    QPushButton *p4_1;
    QPushButton *p2_8;
    QPushButton *p2_7;
    QPushButton *p3_1;
    QPushButton *LaFraise;
    QPushButton *p1;
    QPushButton *p2;
    QPushButton *p5;
    QPushButton *p6;
    QPushButton *p4;
    QPushButton *p7;
    QPushButton *p8;
    QPushButton *p1_2;
    QPushButton *p1_3;
    QPushButton *p1_4;
    QPushButton *p1_6;
    QPushButton *p1_7;
    QPushButton *p3;
    QPushButton *p2_0;
    QPushButton *p2_1;
    QPushButton *p2_2;
    QPushButton *p2_3;
    QPushButton *p2_6;
    QPushButton *p2_5;
    QPushButton *p2_9;
    QPushButton *p4_0;
    QPushButton *p4_2;
    QPushButton *p4_3;
    QPushButton *p4_6;
    QPushButton *p4_7;
    QPushButton *p4_8;
    QPushButton *p4_9;
    QPushButton *p5_1;
    QLabel *label;
    QLabel *label_2;
    QPlainTextEdit *START;
    QLabel *label_3;
    QLabel *label_4;
    QPushButton *Gyro;
    QPushButton *pushButton;
    QLabel *WelcomeTag;
    QPushButton *p5_2;
    QPushButton *out;
    QComboBox *comboBox;
    QPushButton *AddFav;
    QLineEdit *Editor;
    QPushButton *Change;
    QComboBox *Favs;
    QRadioButton *re;
    QRadioButton *rs;
    QLabel *label_5;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MPS)
    {
        if (MPS->objectName().isEmpty())
            MPS->setObjectName("MPS");
        MPS->resize(1548, 743);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MPS->sizePolicy().hasHeightForWidth());
        MPS->setSizePolicy(sizePolicy);
        QIcon icon;
        icon.addFile(QString::fromUtf8("resources/logo.png"), QSize(), QIcon::Normal, QIcon::Off);
        MPS->setWindowIcon(icon);
        MPS->setStyleSheet(QString::fromUtf8("background-color: rgb(250, 246, 238);"));
        centralwidget = new QWidget(MPS);
        centralwidget->setObjectName("centralwidget");
        p1_9 = new QPushButton(centralwidget);
        p1_9->setObjectName("p1_9");
        p1_9->setGeometry(QRect(740, 420, 111, 21));
        p1_9->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        Cinnabon = new QPushButton(centralwidget);
        Cinnabon->setObjectName("Cinnabon");
        Cinnabon->setGeometry(QRect(900, 430, 20, 21));
        Cinnabon->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p1_0 = new QPushButton(centralwidget);
        p1_0->setObjectName("p1_0");
        p1_0->setGeometry(QRect(940, 330, 51, 81));
        p1_0->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        CoffeeBoy = new QPushButton(centralwidget);
        CoffeeBoy->setObjectName("CoffeeBoy");
        CoffeeBoy->setGeometry(QRect(930, 200, 20, 31));
        CoffeeBoy->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        Exit = new QPushButton(centralwidget);
        Exit->setObjectName("Exit");
        Exit->setGeometry(QRect(1460, 250, 61, 31));
        Exit->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p5_0 = new QPushButton(centralwidget);
        p5_0->setObjectName("p5_0");
        p5_0->setGeometry(QRect(1140, 240, 31, 21));
        p5_0->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        Pharamacy = new QPushButton(centralwidget);
        Pharamacy->setObjectName("Pharamacy");
        Pharamacy->setGeometry(QRect(660, 170, 211, 91));
        Pharamacy->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        OpposeMain = new QPushButton(centralwidget);
        OpposeMain->setObjectName("OpposeMain");
        OpposeMain->setGeometry(QRect(1170, 170, 61, 91));
        OpposeMain->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        Shabrawy = new QPushButton(centralwidget);
        Shabrawy->setObjectName("Shabrawy");
        Shabrawy->setGeometry(QRect(890, 200, 20, 31));
        Shabrawy->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        N_ = new QPushButton(centralwidget);
        N_->setObjectName("N_");
        N_->setGeometry(QRect(430, 420, 191, 61));
        N_->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p3_0 = new QPushButton(centralwidget);
        p3_0->setObjectName("p3_0");
        p3_0->setGeometry(QRect(650, 370, 20, 51));
        p3_0->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        K_ = new QPushButton(centralwidget);
        K_->setObjectName("K_");
        K_->setGeometry(QRect(950, 160, 111, 71));
        K_->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        Entry = new QPushButton(centralwidget);
        Entry->setObjectName("Entry");
        Entry->setGeometry(QRect(1450, 180, 71, 81));
        Entry->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        Booth = new QPushButton(centralwidget);
        Booth->setObjectName("Booth");
        Booth->setGeometry(QRect(880, 450, 20, 21));
        Booth->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p2_4 = new QPushButton(centralwidget);
        p2_4->setObjectName("p2_4");
        p2_4->setGeometry(QRect(689, 390, 71, 31));
        p2_4->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p9 = new QPushButton(centralwidget);
        p9->setObjectName("p9");
        p9->setGeometry(QRect(1010, 430, 21, 61));
        p9->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        Main = new QPushButton(centralwidget);
        Main->setObjectName("Main");
        Main->setGeometry(QRect(1030, 280, 191, 201));
        Main->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        sideMain = new QPushButton(centralwidget);
        sideMain->setObjectName("sideMain");
        sideMain->setGeometry(QRect(930, 430, 81, 71));
        sideMain->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        TBS = new QPushButton(centralwidget);
        TBS->setObjectName("TBS");
        TBS->setGeometry(QRect(890, 440, 20, 21));
        TBS->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p1_5 = new QPushButton(centralwidget);
        p1_5->setObjectName("p1_5");
        p1_5->setGeometry(QRect(880, 410, 131, 21));
        p1_5->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        StaffEntry = new QPushButton(centralwidget);
        StaffEntry->setObjectName("StaffEntry");
        StaffEntry->setGeometry(QRect(1440, 450, 81, 81));
        StaffEntry->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p1_8 = new QPushButton(centralwidget);
        p1_8->setObjectName("p1_8");
        p1_8->setGeometry(QRect(640, 260, 61, 51));
        p1_8->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        R2GO = new QPushButton(centralwidget);
        R2GO->setObjectName("R2GO");
        R2GO->setGeometry(QRect(1140, 210, 31, 31));
        R2GO->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        Reception = new QPushButton(centralwidget);
        Reception->setObjectName("Reception");
        Reception->setGeometry(QRect(1160, 280, 61, 131));
        Reception->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        Manousha = new QPushButton(centralwidget);
        Manousha->setObjectName("Manousha");
        Manousha->setGeometry(QRect(910, 200, 20, 31));
        Manousha->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        Mosque = new QPushButton(centralwidget);
        Mosque->setObjectName("Mosque");
        Mosque->setGeometry(QRect(630, 450, 61, 31));
        Mosque->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        Faraghly = new QPushButton(centralwidget);
        Faraghly->setObjectName("Faraghly");
        Faraghly->setGeometry(QRect(870, 470, 20, 21));
        Faraghly->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p1_1 = new QPushButton(centralwidget);
        p1_1->setObjectName("p1_1");
        p1_1->setGeometry(QRect(970, 280, 41, 41));
        p1_1->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p3_5 = new QPushButton(centralwidget);
        p3_5->setObjectName("p3_5");
        p3_5->setGeometry(QRect(560, 300, 16, 121));
        p3_5->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        S_ = new QPushButton(centralwidget);
        S_->setObjectName("S_");
        S_->setGeometry(QRect(380, 150, 241, 151));
        S_->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        MiniMarket = new QPushButton(centralwidget);
        MiniMarket->setObjectName("MiniMarket");
        MiniMarket->setGeometry(QRect(610, 250, 31, 31));
        MiniMarket->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p3_4 = new QPushButton(centralwidget);
        p3_4->setObjectName("p3_4");
        p3_4->setGeometry(QRect(570, 400, 81, 21));
        p3_4->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p3_7 = new QPushButton(centralwidget);
        p3_7->setObjectName("p3_7");
        p3_7->setGeometry(QRect(410, 400, 151, 21));
        p3_7->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p3_6 = new QPushButton(centralwidget);
        p3_6->setObjectName("p3_6");
        p3_6->setGeometry(QRect(410, 300, 151, 101));
        p3_6->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p3_2 = new QPushButton(centralwidget);
        p3_2->setObjectName("p3_2");
        p3_2->setGeometry(QRect(570, 330, 71, 21));
        p3_2->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p3_3 = new QPushButton(centralwidget);
        p3_3->setObjectName("p3_3");
        p3_3->setGeometry(QRect(570, 370, 81, 21));
        p3_3->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        SideS = new QPushButton(centralwidget);
        SideS->setObjectName("SideS");
        SideS->setGeometry(QRect(340, 230, 61, 61));
        SideS->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        R_ = new QPushButton(centralwidget);
        R_->setObjectName("R_");
        R_->setGeometry(QRect(130, 150, 201, 111));
        R_->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        BatatesandZalabya = new QPushButton(centralwidget);
        BatatesandZalabya->setObjectName("BatatesandZalabya");
        BatatesandZalabya->setGeometry(QRect(400, 440, 31, 20));
        BatatesandZalabya->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        Sbarro = new QPushButton(centralwidget);
        Sbarro->setObjectName("Sbarro");
        Sbarro->setGeometry(QRect(310, 449, 41, 21));
        Sbarro->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        FootballField = new QPushButton(centralwidget);
        FootballField->setObjectName("FootballField");
        FootballField->setGeometry(QRect(110, 300, 111, 81));
        FootballField->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        BasketBallCourt = new QPushButton(centralwidget);
        BasketBallCourt->setObjectName("BasketBallCourt");
        BasketBallCourt->setGeometry(QRect(110, 390, 111, 81));
        BasketBallCourt->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        Clinic = new QPushButton(centralwidget);
        Clinic->setObjectName("Clinic");
        Clinic->setGeometry(QRect(50, 290, 51, 31));
        Clinic->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p3_8 = new QPushButton(centralwidget);
        p3_8->setObjectName("p3_8");
        p3_8->setGeometry(QRect(270, 300, 141, 121));
        p3_8->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p3_9 = new QPushButton(centralwidget);
        p3_9->setObjectName("p3_9");
        p3_9->setGeometry(QRect(400, 420, 31, 21));
        p3_9->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p4_4 = new QPushButton(centralwidget);
        p4_4->setObjectName("p4_4");
        p4_4->setGeometry(QRect(170, 380, 51, 21));
        p4_4->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p4_5 = new QPushButton(centralwidget);
        p4_5->setObjectName("p4_5");
        p4_5->setGeometry(QRect(120, 380, 51, 21));
        p4_5->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p4_1 = new QPushButton(centralwidget);
        p4_1->setObjectName("p4_1");
        p4_1->setGeometry(QRect(350, 440, 51, 31));
        p4_1->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p2_8 = new QPushButton(centralwidget);
        p2_8->setObjectName("p2_8");
        p2_8->setGeometry(QRect(400, 460, 31, 21));
        p2_8->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p2_7 = new QPushButton(centralwidget);
        p2_7->setObjectName("p2_7");
        p2_7->setGeometry(QRect(270, 470, 131, 21));
        p2_7->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p3_1 = new QPushButton(centralwidget);
        p3_1->setObjectName("p3_1");
        p3_1->setGeometry(QRect(640, 310, 16, 61));
        p3_1->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        LaFraise = new QPushButton(centralwidget);
        LaFraise->setObjectName("LaFraise");
        LaFraise->setGeometry(QRect(780, 440, 20, 21));
        LaFraise->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p1 = new QPushButton(centralwidget);
        p1->setObjectName("p1");
        p1->setGeometry(QRect(1230, 260, 231, 21));
        p1->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p2 = new QPushButton(centralwidget);
        p2->setObjectName("p2");
        p2->setGeometry(QRect(1280, 450, 161, 81));
        p2->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p5 = new QPushButton(centralwidget);
        p5->setObjectName("p5");
        p5->setGeometry(QRect(1080, 260, 151, 21));
        p5->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p6 = new QPushButton(centralwidget);
        p6->setObjectName("p6");
        p6->setGeometry(QRect(960, 230, 121, 51));
        p6->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p4 = new QPushButton(centralwidget);
        p4->setObjectName("p4");
        p4->setGeometry(QRect(1220, 280, 21, 191));
        p4->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p7 = new QPushButton(centralwidget);
        p7->setObjectName("p7");
        p7->setGeometry(QRect(880, 230, 81, 51));
        p7->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p8 = new QPushButton(centralwidget);
        p8->setObjectName("p8");
        p8->setGeometry(QRect(1010, 280, 21, 151));
        p8->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p1_2 = new QPushButton(centralwidget);
        p1_2->setObjectName("p1_2");
        p1_2->setGeometry(QRect(940, 300, 41, 41));
        p1_2->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p1_3 = new QPushButton(centralwidget);
        p1_3->setObjectName("p1_3");
        p1_3->setGeometry(QRect(910, 330, 41, 41));
        p1_3->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p1_4 = new QPushButton(centralwidget);
        p1_4->setObjectName("p1_4");
        p1_4->setGeometry(QRect(880, 360, 41, 41));
        p1_4->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p1_6 = new QPushButton(centralwidget);
        p1_6->setObjectName("p1_6");
        p1_6->setGeometry(QRect(850, 300, 31, 131));
        p1_6->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p1_7 = new QPushButton(centralwidget);
        p1_7->setObjectName("p1_7");
        p1_7->setGeometry(QRect(700, 260, 181, 41));
        p1_7->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p3 = new QPushButton(centralwidget);
        p3->setObjectName("p3");
        p3->setGeometry(QRect(1220, 470, 61, 51));
        p3->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p2_0 = new QPushButton(centralwidget);
        p2_0->setObjectName("p2_0");
        p2_0->setGeometry(QRect(850, 430, 41, 31));
        p2_0->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p2_1 = new QPushButton(centralwidget);
        p2_1->setObjectName("p2_1");
        p2_1->setGeometry(QRect(720, 460, 151, 31));
        p2_1->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p2_2 = new QPushButton(centralwidget);
        p2_2->setObjectName("p2_2");
        p2_2->setGeometry(QRect(720, 440, 61, 21));
        p2_2->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p2_3 = new QPushButton(centralwidget);
        p2_3->setObjectName("p2_3");
        p2_3->setGeometry(QRect(690, 440, 31, 61));
        p2_3->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p2_6 = new QPushButton(centralwidget);
        p2_6->setObjectName("p2_6");
        p2_6->setGeometry(QRect(400, 480, 221, 21));
        p2_6->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p2_5 = new QPushButton(centralwidget);
        p2_5->setObjectName("p2_5");
        p2_5->setGeometry(QRect(620, 480, 71, 21));
        p2_5->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p2_9 = new QPushButton(centralwidget);
        p2_9->setObjectName("p2_9");
        p2_9->setGeometry(QRect(670, 310, 21, 111));
        p2_9->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p4_0 = new QPushButton(centralwidget);
        p4_0->setObjectName("p4_0");
        p4_0->setGeometry(QRect(250, 420, 151, 21));
        p4_0->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p4_2 = new QPushButton(centralwidget);
        p4_2->setObjectName("p4_2");
        p4_2->setGeometry(QRect(240, 440, 71, 31));
        p4_2->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p4_3 = new QPushButton(centralwidget);
        p4_3->setObjectName("p4_3");
        p4_3->setGeometry(QRect(220, 360, 31, 81));
        p4_3->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p4_6 = new QPushButton(centralwidget);
        p4_6->setObjectName("p4_6");
        p4_6->setGeometry(QRect(220, 300, 51, 61));
        p4_6->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p4_7 = new QPushButton(centralwidget);
        p4_7->setObjectName("p4_7");
        p4_7->setGeometry(QRect(250, 360, 21, 61));
        p4_7->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p4_8 = new QPushButton(centralwidget);
        p4_8->setObjectName("p4_8");
        p4_8->setGeometry(QRect(130, 260, 211, 41));
        p4_8->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p4_9 = new QPushButton(centralwidget);
        p4_9->setObjectName("p4_9");
        p4_9->setGeometry(QRect(40, 240, 91, 51));
        p4_9->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        p5_1 = new QPushButton(centralwidget);
        p5_1->setObjectName("p5_1");
        p5_1->setGeometry(QRect(800, 440, 51, 21));
        p5_1->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        label = new QLabel(centralwidget);
        label->setObjectName("label");
        label->setGeometry(QRect(620, 40, 401, 41));
        label->setStyleSheet(QString::fromUtf8("font: 24pt \"Agency FB\";\n"
"background-color: rgb(250, 246, 238);"));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(20, 550, 191, 41));
        label_2->setStyleSheet(QString::fromUtf8("font: 18pt \"Agency FB\";"));
        label_2->setScaledContents(true);
        START = new QPlainTextEdit(centralwidget);
        START->setObjectName("START");
        START->setGeometry(QRect(130, 560, 201, 31));
        START->setStyleSheet(QString::fromUtf8("font: 14pt \"Agency FB\";\n"
"background-color: rgb(252, 254, 255);"));
        START->setReadOnly(false);
        START->setOverwriteMode(false);
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(360, 560, 361, 41));
        label_3->setStyleSheet(QString::fromUtf8("font: 18pt \"Agency FB\";"));
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(610, 640, 431, 61));
        label_4->setStyleSheet(QString::fromUtf8("font: 18pt \"Agency FB\";"));
        label_4->setTextFormat(Qt::PlainText);
        Gyro = new QPushButton(centralwidget);
        Gyro->setObjectName("Gyro");
        Gyro->setGeometry(QRect(230, 300, 21, 21));
        Gyro->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        pushButton = new QPushButton(centralwidget);
        pushButton->setObjectName("pushButton");
        pushButton->setGeometry(QRect(960, 570, 141, 41));
        pushButton->setStyleSheet(QString::fromUtf8("font: 18pt \"Agency FB\";\n"
"background-color: rgb(252, 254, 255);"));
        WelcomeTag = new QLabel(centralwidget);
        WelcomeTag->setObjectName("WelcomeTag");
        WelcomeTag->setGeometry(QRect(50, 30, 471, 61));
        QFont font;
        font.setFamilies({QString::fromUtf8("Agency FB")});
        font.setPointSize(18);
        font.setBold(false);
        font.setItalic(false);
        WelcomeTag->setFont(font);
        WelcomeTag->setStyleSheet(QString::fromUtf8("font: 18pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(250, 246, 238);"));
        WelcomeTag->setWordWrap(true);
        p5_2 = new QPushButton(centralwidget);
        p5_2->setObjectName("p5_2");
        p5_2->setGeometry(QRect(450, 300, 61, 121));
        p5_2->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        out = new QPushButton(centralwidget);
        out->setObjectName("out");
        out->setGeometry(QRect(20, 120, 1501, 421));
        out->setStyleSheet(QString::fromUtf8("QPushButton{background:transparent;}"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Images/map.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        out->setIcon(icon1);
        comboBox = new QComboBox(centralwidget);
        comboBox->setObjectName("comboBox");
        comboBox->setGeometry(QRect(720, 570, 231, 26));
        comboBox->setStyleSheet(QString::fromUtf8("font: 18pt \"Agency FB\";\n"
"background-color: rgb(252, 254, 255);"));
        AddFav = new QPushButton(centralwidget);
        AddFav->setObjectName("AddFav");
        AddFav->setGeometry(QRect(1350, 570, 161, 41));
        AddFav->setStyleSheet(QString::fromUtf8("font: 18pt \"Agency FB\";\n"
"background-color: rgb(252, 254, 255);"));
        Editor = new QLineEdit(centralwidget);
        Editor->setObjectName("Editor");
        Editor->setGeometry(QRect(1120, 610, 221, 26));
        Editor->setStyleSheet(QString::fromUtf8("font: 18pt \"Agency FB\";\n"
"background-color: rgb(252, 254, 255);"));
        Change = new QPushButton(centralwidget);
        Change->setObjectName("Change");
        Change->setGeometry(QRect(1140, 650, 171, 41));
        Change->setStyleSheet(QString::fromUtf8("font: 18pt \"Agency FB\";\n"
"background-color: rgb(252, 254, 255);"));
        Favs = new QComboBox(centralwidget);
        Favs->setObjectName("Favs");
        Favs->setGeometry(QRect(1110, 570, 231, 26));
        Favs->setStyleSheet(QString::fromUtf8("font: 16pt \"Agency FB\";\n"
"background-color: rgb(252, 254, 255);"));
        re = new QRadioButton(centralwidget);
        re->setObjectName("re");
        re->setGeometry(QRect(1360, 650, 110, 24));
        re->setStyleSheet(QString::fromUtf8("font: 18pt \"Agency FB\";"));
        rs = new QRadioButton(centralwidget);
        rs->setObjectName("rs");
        rs->setGeometry(QRect(1360, 620, 110, 24));
        rs->setStyleSheet(QString::fromUtf8("font: 18pt \"Agency FB\";"));
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(20, 120, 1501, 421));
        label_5->setPixmap(QPixmap(QString::fromUtf8(":/Images/map.jpg")));
        label_5->setScaledContents(true);
        MPS->setCentralWidget(centralwidget);
        label_5->raise();
        out->raise();
        label_3->raise();
        comboBox->raise();
        p1_9->raise();
        Cinnabon->raise();
        p1_0->raise();
        CoffeeBoy->raise();
        Exit->raise();
        p5_0->raise();
        Pharamacy->raise();
        OpposeMain->raise();
        Shabrawy->raise();
        N_->raise();
        p3_0->raise();
        K_->raise();
        Entry->raise();
        Booth->raise();
        p2_4->raise();
        p9->raise();
        Main->raise();
        sideMain->raise();
        TBS->raise();
        p1_5->raise();
        StaffEntry->raise();
        p1_8->raise();
        R2GO->raise();
        Reception->raise();
        Manousha->raise();
        Mosque->raise();
        Faraghly->raise();
        p1_1->raise();
        p3_5->raise();
        S_->raise();
        MiniMarket->raise();
        p3_4->raise();
        p3_7->raise();
        p3_2->raise();
        p3_3->raise();
        SideS->raise();
        R_->raise();
        BatatesandZalabya->raise();
        Sbarro->raise();
        FootballField->raise();
        BasketBallCourt->raise();
        Clinic->raise();
        p3_8->raise();
        p3_9->raise();
        p4_4->raise();
        p4_5->raise();
        p4_1->raise();
        p2_8->raise();
        p2_7->raise();
        p3_1->raise();
        LaFraise->raise();
        p1->raise();
        p2->raise();
        p5->raise();
        p6->raise();
        p4->raise();
        p7->raise();
        p8->raise();
        p1_2->raise();
        p1_3->raise();
        p1_4->raise();
        p1_6->raise();
        p1_7->raise();
        p3->raise();
        p2_0->raise();
        p2_1->raise();
        p2_2->raise();
        p2_3->raise();
        p2_6->raise();
        p2_5->raise();
        p2_9->raise();
        p4_0->raise();
        p4_2->raise();
        p4_3->raise();
        p4_6->raise();
        p4_7->raise();
        p4_8->raise();
        p4_9->raise();
        p5_1->raise();
        label->raise();
        label_2->raise();
        START->raise();
        label_4->raise();
        Gyro->raise();
        pushButton->raise();
        WelcomeTag->raise();
        p5_2->raise();
        p3_6->raise();
        AddFav->raise();
        Editor->raise();
        Favs->raise();
        Change->raise();
        re->raise();
        rs->raise();
        menubar = new QMenuBar(MPS);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 1548, 22));
        MPS->setMenuBar(menubar);
        statusbar = new QStatusBar(MPS);
        statusbar->setObjectName("statusbar");
        MPS->setStatusBar(statusbar);

        retranslateUi(MPS);

        QMetaObject::connectSlotsByName(MPS);
    } // setupUi

    void retranslateUi(QMainWindow *MPS)
    {
        MPS->setWindowTitle(QCoreApplication::translate("MPS", "MPS", nullptr));
        p1_9->setText(QString());
        Cinnabon->setText(QString());
        p1_0->setText(QString());
        CoffeeBoy->setText(QString());
        Exit->setText(QString());
        p5_0->setText(QString());
        Pharamacy->setText(QString());
        OpposeMain->setText(QString());
        Shabrawy->setText(QString());
        N_->setText(QString());
        p3_0->setText(QString());
        K_->setText(QString());
        Entry->setText(QString());
        Booth->setText(QString());
        p2_4->setText(QString());
        p9->setText(QString());
        Main->setText(QString());
        sideMain->setText(QString());
        TBS->setText(QString());
        p1_5->setText(QString());
        StaffEntry->setText(QString());
        p1_8->setText(QString());
        R2GO->setText(QString());
        Reception->setText(QString());
        Manousha->setText(QString());
        Mosque->setText(QString());
        Faraghly->setText(QString());
        p1_1->setText(QString());
        p3_5->setText(QString());
        S_->setText(QString());
        MiniMarket->setText(QString());
        p3_4->setText(QString());
        p3_7->setText(QString());
        p3_6->setText(QString());
        p3_2->setText(QString());
        p3_3->setText(QString());
        SideS->setText(QString());
        R_->setText(QString());
        BatatesandZalabya->setText(QString());
        Sbarro->setText(QString());
        FootballField->setText(QString());
        BasketBallCourt->setText(QString());
        Clinic->setText(QString());
        p3_8->setText(QString());
        p3_9->setText(QString());
        p4_4->setText(QString());
        p4_5->setText(QString());
        p4_1->setText(QString());
        p2_8->setText(QString());
        p2_7->setText(QString());
        p3_1->setText(QString());
        LaFraise->setText(QString());
        p1->setText(QString());
        p2->setText(QString());
        p5->setText(QString());
        p6->setText(QString());
        p4->setText(QString());
        p7->setText(QString());
        p8->setText(QString());
        p1_2->setText(QString());
        p1_3->setText(QString());
        p1_4->setText(QString());
        p1_6->setText(QString());
        p1_7->setText(QString());
        p3->setText(QString());
        p2_0->setText(QString());
        p2_1->setText(QString());
        p2_2->setText(QString());
        p2_3->setText(QString());
        p2_6->setText(QString());
        p2_5->setText(QString());
        p2_9->setText(QString());
        p4_0->setText(QString());
        p4_2->setText(QString());
        p4_3->setText(QString());
        p4_6->setText(QString());
        p4_7->setText(QString());
        p4_8->setText(QString());
        p4_9->setText(QString());
        p5_1->setText(QString());
        label->setText(QCoreApplication::translate("MPS", "MPS : MIU Positioning System", nullptr));
        label_2->setText(QCoreApplication::translate("MPS", "You are at :", nullptr));
        START->setPlainText(QCoreApplication::translate("MPS", "node at button selected", nullptr));
        label_3->setText(QCoreApplication::translate("MPS", "Please select your desired destination :", nullptr));
        label_4->setText(QString());
        Gyro->setText(QString());
        pushButton->setText(QCoreApplication::translate("MPS", "Search", nullptr));
        WelcomeTag->setText(QString());
        p5_2->setText(QString());
        out->setText(QString());
        AddFav->setText(QCoreApplication::translate("MPS", "Add to Favorites", nullptr));
        Change->setText(QCoreApplication::translate("MPS", "Change Name", nullptr));
        re->setText(QCoreApplication::translate("MPS", "End", nullptr));
        rs->setText(QCoreApplication::translate("MPS", "Start", nullptr));
        label_5->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MPS: public Ui_MPS {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MPS_H
